title: Qihang's site
navbar_title: Qihang Wang's

author:
  name: Qihang Wang # Your name
  email: worlesenric@gmail.com

description: Here we go # description of your site

url: "https://worles.github.io" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # The subpath of your site, e.g. /blog

jekyllacademic:
  homepage_title: "Blog & Notes" # Your homepage title
  disqusname: # Your disqus sitename
  footer: Qihang Wang, 2024 # Your name, Year
  contentlicense: "MIT" # Choose either one of these to put: MIT, Commons Clause, CC BY 4.0, CC BY-NC 4.0, CC BY-ND 4.0, CC BY-NC-ND 4.0, CC BY-NC-SA 4.0, CC BY-NC-SA 4.0, CC BY-SA 4.0
  socials:
    twitter: worles_enric # Your twitter username
    github: worlesenric # Your github username
    linkedin: unavailable # Your linkedin
    keybase: keybase # Your keybase

# No need to edit this part, however if you want to, that's fine as well

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
    future: true
  projects:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
